package com.example.onepieceapp

enum class Lang { FR, EN }

data class AppStrings(
    val appTitle: String,
    val subtitle: String,
    val modeFacile: String,
    val modeMoyen: String,
    val modeDifficile: String,
    val modeQuotidien: String,
    val modeDieu: String,
    val chooseMode: String,
    val changeMode: String,
    val searchLabel: String,
    val searchLabelDuringGame: String,
    val hintButton: String,
    val winMessage: (String) -> String,
    val essais: String,
    val yesterdayCharacter: String,
    val solvedToday: String,
    val colPersonnage: String,
    val colFruit: String,
    val colHaki: String,
    val colArc: String,
    val colPrime: String,
    val colAffiliation: String,
    val colTaille: String,
    val hintDisponible: String,
    val hintTries: (Int) -> String,
    val after: String,
    val before: String,
    val moreThan: String,
    val lessThan: String,
    val languageName: String,
    // Authentification
    val authTitle: String,
    val emailLabel: String,
    val passwordLabel: String,
    val loginButton: String,
    val signUpButton: String,
    val switchToSignUp: String,
    val switchToLogin: String,
    // Statistiques
    val statsTitle: String,
    val gamesPlayed: String,
    val gamesWon: String,
    val winRate: String,
    val currentStreak: String,
    val maxStreak: String,
    val averageGuesses: String,
    val signOut: String,
    val close: String,
    val profile: String,
    val dailyGlobalSolved: (Int, Double) -> String,
    // Amis
    val usernameLabel: String,
    val usernameTaken: String,
    val usernameAvailable: String,
    val chooseUsernamePrompt: String,
    val saveUsername: String,
    val friendsTab: String,
    val profileTab: String,
    val addFriend: String,
    val addFriendHint: String,
    val sendRequest: String,
    val incomingRequests: String,
    val noIncomingRequests: String,
    val accept: String,
    val decline: String,
    val myFriends: String,
    val noFriends: String,
    val removeFriend: String,
    val leaderboardTitle: String,
    val you: String,
    val friendRequestSent: String,
    val dailyDoneTitle: String,
    val dailyDoneCharacter: (String) -> String,
    val comeBackTomorrow: String,
    // Révélation via pub
    val revealButton: String,
    val watchAdTitle: String,
    val watchAdMessage: String,
    val watchAdConfirm: String,
    val watchAdCancel: String,
    val watchingAdMessage: String,
    val revealedMessage: (String) -> String
)

val FR_STRINGS = AppStrings(
    appTitle = "One Piecedle",
    subtitle = "Devine le personnage choisi par l'appli. Vert = trouvé, orange = partiellement correct, rouge = faux (avec indice).",
    modeFacile = "Facile",
    modeMoyen = "Moyen",
    modeDifficile = "Difficile",
    modeQuotidien = "Quotidien",
    modeDieu = "Dieu",
    chooseMode = "Choisis un mode de jeu pour commencer",
    changeMode = "Changer de mode",
    searchLabel = "Entre un personnage One Piece",
    searchLabelDuringGame = "Personnage suivant…",
    hintButton = "Indice",
    winMessage = { name -> "Bravo ! Le personnage était bien $name" },
    essais = "Essais",
    yesterdayCharacter = "Personnage d'hier",
    solvedToday = "Résolutions du quotidien (sur cet appareil)",
    colPersonnage = "Personnage",
    colFruit = "Fruit du démon",
    colHaki = "Haki",
    colArc = "Premier arc",
    colPrime = "Prime",
    colAffiliation = "Affiliation",
    colTaille = "Taille",
    hintDisponible = "Indice disponible",
    hintTries = { n -> if (n == 1) "Prochain indice dans $n essai" else "Prochain indice dans $n essais" },
    after = "Après",
    before = "Avant",
    moreThan = "Plus que",
    lessThan = "Moins que",
    languageName = "FR",
    authTitle = "Connexion",
    emailLabel = "Email",
    passwordLabel = "Mot de passe",
    loginButton = "Se connecter",
    signUpButton = "Créer un compte",
    switchToSignUp = "Pas de compte ? Inscris-toi",
    switchToLogin = "Déjà un compte ? Connecte-toi",
    statsTitle = "Statistiques",
    gamesPlayed = "Parties jouées",
    gamesWon = "Parties gagnées",
    winRate = "Taux de victoire",
    currentStreak = "Série en cours",
    maxStreak = "Meilleure série",
    averageGuesses = "Essais en moyenne",
    signOut = "Se déconnecter",
    close = "Fermer",
    profile = "Profil",
    dailyGlobalSolved = { count, avg ->
        if (count == 0) "Sois le premier à le trouver aujourd'hui !"
        else "Trouvé par $count joueur${if (count > 1) "s" else ""} (${"%.1f".format(avg)} essais en moyenne)"
    },
    usernameLabel = "Pseudo",
    usernameTaken = "Ce pseudo est déjà pris",
    usernameAvailable = "Pseudo disponible",
    chooseUsernamePrompt = "Choisis un pseudo pour pouvoir ajouter des amis",
    saveUsername = "Valider",
    friendsTab = "Amis",
    profileTab = "Profil",
    addFriend = "Ajouter un ami",
    addFriendHint = "Pseudo de ton ami",
    sendRequest = "Envoyer",
    incomingRequests = "Demandes reçues",
    noIncomingRequests = "Aucune demande en attente",
    accept = "Accepter",
    decline = "Refuser",
    myFriends = "Mes amis",
    noFriends = "Tu n'as pas encore d'amis",
    removeFriend = "Retirer",
    leaderboardTitle = "Classement entre amis",
    you = "Toi",
    friendRequestSent = "Demande envoyée !",
    dailyDoneTitle = "Quotidien déjà joué aujourd'hui !",
    dailyDoneCharacter = { name -> "Le personnage du jour était $name" },
    comeBackTomorrow = "Reviens demain pour un nouveau personnage !",
    revealButton = "Révéler (pub)",
    watchAdTitle = "Révéler le personnage",
    watchAdMessage = "Regarde une courte pub pour révéler immédiatement le personnage.",
    watchAdConfirm = "Regarder la pub",
    watchAdCancel = "Annuler",
    watchingAdMessage = "Lecture de la pub…",
    revealedMessage = { name -> "Personnage révélé : $name" }
)

val EN_STRINGS = AppStrings(
    appTitle = "One Piecedle",
    subtitle = "Guess the character the app picked. Green = found, orange = partially correct, red = wrong (with a hint).",
    modeFacile = "Easy",
    modeMoyen = "Medium",
    modeDifficile = "Hard",
    modeQuotidien = "Daily",
    modeDieu = "God",
    chooseMode = "Pick a game mode to start",
    changeMode = "Change mode",
    searchLabel = "Enter a One Piece character",
    searchLabelDuringGame = "Next character…",
    hintButton = "Hint",
    winMessage = { name -> "Well done! The character was $name" },
    essais = "Guesses",
    yesterdayCharacter = "Yesterday's character",
    solvedToday = "Daily solves (this device)",
    colPersonnage = "Character",
    colFruit = "Devil Fruit",
    colHaki = "Haki",
    colArc = "First arc",
    colPrime = "Bounty",
    colAffiliation = "Affiliation",
    colTaille = "Height",
    hintDisponible = "Hint available",
    hintTries = { n -> if (n == 1) "Next hint in $n try" else "Next hint in $n tries" },
    after = "After",
    before = "Before",
    moreThan = "More than",
    lessThan = "Less than",
    languageName = "EN",
    authTitle = "Sign in",
    emailLabel = "Email",
    passwordLabel = "Password",
    loginButton = "Log in",
    signUpButton = "Create account",
    switchToSignUp = "No account? Sign up",
    switchToLogin = "Already have an account? Log in",
    statsTitle = "Statistics",
    gamesPlayed = "Games played",
    gamesWon = "Games won",
    winRate = "Win rate",
    currentStreak = "Current streak",
    maxStreak = "Best streak",
    averageGuesses = "Average guesses",
    signOut = "Sign out",
    close = "Close",
    profile = "Profile",
    dailyGlobalSolved = { count, avg ->
        if (count == 0) "Be the first to find it today!"
        else "Solved by $count player${if (count > 1) "s" else ""} (${"%.1f".format(avg)} guesses on average)"
    },
    usernameLabel = "Username",
    usernameTaken = "This username is already taken",
    usernameAvailable = "Username available",
    chooseUsernamePrompt = "Pick a username so you can add friends",
    saveUsername = "Save",
    friendsTab = "Friends",
    profileTab = "Profile",
    addFriend = "Add a friend",
    addFriendHint = "Friend's username",
    sendRequest = "Send",
    incomingRequests = "Incoming requests",
    noIncomingRequests = "No pending requests",
    accept = "Accept",
    decline = "Decline",
    myFriends = "My friends",
    noFriends = "You don't have any friends yet",
    removeFriend = "Remove",
    leaderboardTitle = "Friends leaderboard",
    you = "You",
    friendRequestSent = "Request sent!",
    dailyDoneTitle = "Daily already played today!",
    dailyDoneCharacter = { name -> "Today's character was $name" },
    comeBackTomorrow = "Come back tomorrow for a new character!",
    revealButton = "Reveal (ad)",
    watchAdTitle = "Reveal the character",
    watchAdMessage = "Watch a short ad to immediately reveal the character.",
    watchAdConfirm = "Watch ad",
    watchAdCancel = "Cancel",
    watchingAdMessage = "Playing ad…",
    revealedMessage = { name -> "Character revealed: $name" }
)

fun stringsFor(lang: Lang): AppStrings = if (lang == Lang.FR) FR_STRINGS else EN_STRINGS
